# Generated by Django 6.0.3 on 2026-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layer_type', models.CharField(choices=[('roads', 'Đường'), ('lights', 'Đèn GT'), ('flood', 'Ngập lụt'), ('infra', 'Hạ tầng'), ('weather', 'Thời tiết')], max_length=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('style_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Lớp bản đồ',
            },
        ),
    ]
