# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tích hợp')),
                ('api_key', models.CharField(blank=True, max_length=300, verbose_name='API Key')),
                ('endpoint', models.URLField(blank=True, verbose_name='Endpoint URL')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('error', 'Lỗi')], default='inactive', max_length=10, verbose_name='Trạng thái')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Đồng bộ lần cuối')),
                ('error_message', models.TextField(blank=True, verbose_name='Lỗi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tích hợp API',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='integration.apiintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
