# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('flood', 'Lũ lụt'), ('storm', 'Bão'), ('earthquake', 'Động đất'), ('other', 'Khác')], max_length=15, verbose_name='Loại thiên tai')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('affected_areas', models.TextField(blank=True, verbose_name='Khu vực bị ảnh hưởng')),
                ('casualties', models.TextField(blank=True, verbose_name='Tình trạng nạn nhân')),
                ('infra_status', models.TextField(blank=True, verbose_name='Tình trạng hạ tầng')),
                ('service_status', models.TextField(blank=True, verbose_name='Tình trạng dịch vụ (y tế, điện, nước)')),
                ('power_status', models.TextField(blank=True, verbose_name='Tình trạng điện')),
                ('areas_needing_help', models.TextField(blank=True, verbose_name='Khu vực cần hỗ trợ')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã đăng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cập nhật thiên tai',
                'verbose_name_plural': 'Cập nhật thiên tai',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('level', models.CharField(choices=[('1', 'Cấp 1 - Theo dõi'), ('2', 'Cấp 2 - Cảnh báo'), ('3', 'Cấp 3 - Nguy hiểm'), ('4', 'Cấp 4 - Rất nguy hiểm')], default='1', max_length=2, verbose_name='Cấp độ')),
                ('area_type', models.CharField(choices=[('district', 'Quận/Huyện'), ('ward', 'Phường/Xã'), ('road', 'Tuyến đường'), ('infra', 'Hạ tầng')], default='district', max_length=10, verbose_name='Loại khu vực')),
                ('area_name', models.CharField(max_length=200, verbose_name='Tên khu vực')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('water_level_cm', models.IntegerField(blank=True, null=True, verbose_name='Mực nước (cm)')),
                ('safe_routes', models.TextField(blank=True, verbose_name='Tuyến đường an toàn')),
                ('evacuation_info', models.TextField(blank=True, verbose_name='Thông tin sơ tán')),
                ('shelter_locations', models.TextField(blank=True, verbose_name='Địa điểm trú ẩn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_sent_sms', models.BooleanField(default=False, verbose_name='Đã gửi SMS')),
                ('rescue_teams_notified', models.BooleanField(default=False, verbose_name='Đã thông báo đội cứu hộ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cảnh báo ngập lụt',
                'verbose_name_plural': 'Cảnh báo ngập lụt',
                'ordering': ['-created_at'],
            },
        ),
    ]
