# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, max_length=50, verbose_name='Số giấy phép')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả công trình')),
                ('contractor_name', models.CharField(blank=True, max_length=200, verbose_name='Tên nhà thầu')),
                ('location', models.CharField(max_length=300, verbose_name='Địa điểm thi công')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã nộp'), ('received', 'Đã tiếp nhận'), ('reviewing', 'Đang xét duyệt'), ('additional_required', 'Cần bổ sung'), ('approved', 'Đã phê duyệt'), ('rejected', 'Từ chối'), ('construction', 'Đang thi công'), ('completed', 'Hoàn thành'), ('suspended', 'Tạm dừng')], default='draft', max_length=25, verbose_name='Trạng thái')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('additional_required', models.TextField(blank=True, verbose_name='Yêu cầu bổ sung')),
                ('violation_warning', models.TextField(blank=True, verbose_name='Cảnh báo vi phạm')),
                ('impact_assessment', models.TextField(blank=True, verbose_name='Đánh giá tác động hạ tầng')),
                ('progress_report', models.TextField(blank=True, verbose_name='Báo cáo tiến độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_applications', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permits', to=settings.AUTH_USER_MODEL)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giấy phép thi công',
                'verbose_name_plural': 'Giấy phép thi công',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên tài liệu')),
                ('file', models.FileField(upload_to='permits/documents/', verbose_name='Tệp')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='permits.constructionpermit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài liệu hồ sơ',
            },
        ),
    ]
