# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà thầu')),
                ('tax_code', models.CharField(max_length=20, unique=True, verbose_name='Mã số thuế')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('representative', models.CharField(blank=True, max_length=100, verbose_name='Người đại diện')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhà thầu',
                'verbose_name_plural': 'Nhà thầu',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Số hợp đồng')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hiệu lực'), ('completed', 'Hoàn thành'), ('terminated', 'Chấm dứt'), ('expired', 'Hết hạn')], default='draft', max_length=15, verbose_name='Trạng thái')),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá trị (VNĐ)')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('terms', models.TextField(blank=True, verbose_name='Điều khoản')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('guaranty', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Bảo lãnh')),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Tài liệu hợp đồng')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='Tiến độ (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contractor')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Hợp đồng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề gói thầu')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Ngân sách (VNĐ)')),
                ('deadline', models.DateTimeField(verbose_name='Hạn nộp hồ sơ')),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã đóng'), ('awarded', 'Đã trao thầu'), ('cancelled', 'Hủy')], default='open', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_tenders', to='contracts.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('result_contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Gói thầu',
                'verbose_name_plural': 'Gói thầu',
                'ordering': ['-created_at'],
            },
        ),
    ]
