# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Ẩn danh')),
                ('rating', models.IntegerField(verbose_name='Đánh giá (1-5)')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Phân loại')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('reviewed', 'Đã xem xét'), ('resolved', 'Đã xử lý'), ('hidden', 'Đã ẩn')], default='new', max_length=10, verbose_name='Trạng thái')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Phản hồi quản trị')),
                ('is_important', models.BooleanField(default=False, verbose_name='Quan trọng')),
                ('is_spam', models.BooleanField(default=False, verbose_name='Spam')),
                ('likes', models.IntegerField(default=0, verbose_name='Lượt thích')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phản hồi hệ thống',
                'verbose_name_plural': 'Phản hồi hệ thống',
                'ordering': ['-created_at'],
            },
        ),
    ]
