# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
                ('description', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('contract_type', models.CharField(blank=True, max_length=50, verbose_name='Loại hợp đồng')),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương (VNĐ)')),
                ('phone_work', models.CharField(blank=True, max_length=15, verbose_name='SĐT công việc')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name='Liên hệ khẩn cấp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Phép năm'), ('sick', 'Nghỉ bệnh'), ('unpaid', 'Không lương'), ('other', 'Khác')], max_length=10, verbose_name='Loại phép')),
                ('start_date', models.DateField(verbose_name='Từ ngày')),
                ('end_date', models.DateField(verbose_name='Đến ngày')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Đơn nghỉ phép',
                'verbose_name_plural': 'Đơn nghỉ phép',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Khóa đào tạo')),
                ('description', models.TextField(blank=True)),
                ('trainer', models.CharField(blank=True, max_length=100, verbose_name='Giảng viên')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('certificate_required', models.BooleanField(default=False, verbose_name='Cấp chứng chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='trainings', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Đào tạo',
                'verbose_name_plural': 'Đào tạo',
            },
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn hoàn thành')),
                ('status', models.CharField(choices=[('todo', 'Chưa làm'), ('in_progress', 'Đang làm'), ('done', 'Hoàn thành'), ('cancelled', 'Hủy')], default='todo', max_length=15, verbose_name='Trạng thái')),
                ('completion_note', models.TextField(blank=True, verbose_name='Ghi chú hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Phân công công việc',
                'verbose_name_plural': 'Phân công công việc',
                'ordering': ['due_date'],
            },
        ),
    ]
