# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên vật tư')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('m', 'm'), ('m2', 'm²'), ('m3', 'm³'), ('cai', 'Cái'), ('cuon', 'Cuộn'), ('thung', 'Thùng')], default='cai', max_length=10, verbose_name='Đơn vị')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá (VNĐ)')),
                ('current_stock', models.FloatField(default=0, verbose_name='Tồn kho')),
                ('min_stock', models.FloatField(default=10, verbose_name='Tồn kho tối thiểu')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vật tư',
                'verbose_name_plural': 'Vật tư',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='SĐT')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Nhập kho'), ('out', 'Xuất kho'), ('adjust', 'Điều chỉnh')], max_length=10, verbose_name='Loại')),
                ('quantity', models.FloatField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Lý do')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Số hóa đơn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='maintenance.maintenancerequest')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.material')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giao dịch kho',
                'verbose_name_plural': 'Giao dịch kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
