# Generated by Django 6.0.3 on 2026-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mẫu báo cáo')),
                ('report_type', models.CharField(choices=[('monthly', 'Tháng'), ('quarterly', 'Quý'), ('yearly', 'Năm'), ('custom', 'Tùy chỉnh')], max_length=15, verbose_name='Loại')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mẫu báo cáo',
            },
        ),
    ]
