# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Danh mục')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Danh mục tài liệu',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Tệp')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Phiên bản')),
                ('is_public', models.BooleanField(default=False, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='infrastructure.infrastructure')),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='infrastructure.road')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-created_at'],
            },
        ),
    ]
