# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại hạ tầng',
                'verbose_name_plural': 'Loại hạ tầng',
            },
        ),
        migrations.CreateModel(
            name='ManagementZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khu vực')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_zones', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý')),
            ],
            options={
                'verbose_name': 'Khu vực quản lý',
                'verbose_name_plural': 'Khu vực quản lý',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã')),
                ('status', models.CharField(choices=[('good', 'Tốt'), ('normal', 'Bình thường'), ('needs_repair', 'Cần sửa chữa'), ('critical', 'Nguy hiểm')], default='good', max_length=15, verbose_name='Trạng thái')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Ngày lắp đặt')),
                ('managing_unit', models.CharField(blank=True, max_length=200, verbose_name='Đơn vị quản lý')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('expected_lifespan_years', models.IntegerField(default=20, verbose_name='Tuổi thọ dự kiến (năm)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.infrastructuretype', verbose_name='Loại')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.managementzone')),
            ],
            options={
                'verbose_name': 'Hạ tầng',
                'verbose_name_plural': 'Hạ tầng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đường')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã đường')),
                ('direction', models.CharField(choices=[('one_way', 'Một chiều'), ('two_way', 'Hai chiều'), ('railway', 'Đường sắt')], default='two_way', max_length=10, verbose_name='Loại đường')),
                ('status', models.CharField(choices=[('good', 'Tốt'), ('normal', 'Bình thường'), ('bad', 'Xấu'), ('critical', 'Nguy hiểm'), ('under_repair', 'Đang sửa chữa')], default='good', max_length=20, verbose_name='Tình trạng')),
                ('quality_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Điểm chất lượng (1-5)')),
                ('length_km', models.FloatField(default=0, verbose_name='Chiều dài (km)')),
                ('width_m', models.FloatField(default=0, verbose_name='Chiều rộng (m)')),
                ('lanes', models.IntegerField(default=2, verbose_name='Số làn')),
                ('built_year', models.IntegerField(blank=True, null=True, verbose_name='Năm xây dựng')),
                ('last_repaired', models.DateField(blank=True, null=True, verbose_name='Sửa chữa lần cuối')),
                ('traffic_density', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('very_high', 'Rất cao')], default='medium', max_length=20, verbose_name='Mật độ giao thông')),
                ('managing_unit', models.CharField(blank=True, max_length=200, verbose_name='Đơn vị quản lý')),
                ('start_point', models.CharField(blank=True, max_length=200, verbose_name='Điểm đầu')),
                ('end_point', models.CharField(blank=True, max_length=200, verbose_name='Điểm cuối')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roads', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roads', to='infrastructure.managementzone', verbose_name='Khu vực')),
            ],
            options={
                'verbose_name': 'Tuyến đường',
                'verbose_name_plural': 'Tuyến đường',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('severity', models.CharField(choices=[('minor', 'Nhẹ'), ('moderate', 'Trung bình'), ('severe', 'Nghiêm trọng'), ('critical', 'Rất nghiêm trọng')], default='minor', max_length=10, verbose_name='Mức độ')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='potholes/', verbose_name='Ảnh')),
                ('is_repaired', models.BooleanField(default=False, verbose_name='Đã sửa')),
                ('repaired_at', models.DateField(blank=True, null=True, verbose_name='Ngày sửa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_potholes', to=settings.AUTH_USER_MODEL)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potholes', to='infrastructure.road', verbose_name='Tuyến đường')),
            ],
            options={
                'verbose_name': 'Ổ gà',
                'verbose_name_plural': 'Ổ gà',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadRepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField(verbose_name='Ngày sửa chữa')),
                ('description', models.TextField(verbose_name='Nội dung sửa chữa')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Chi phí (VNĐ)')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Đơn vị thi công')),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='repairs/before/', verbose_name='Ảnh trước')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='repairs/after/', verbose_name='Ảnh sau')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_history', to='infrastructure.road', verbose_name='Tuyến đường')),
            ],
            options={
                'verbose_name': 'Lịch sử sửa chữa',
                'verbose_name_plural': 'Lịch sử sửa chữa',
                'ordering': ['-repair_date'],
            },
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã đèn')),
                ('location', models.CharField(max_length=300, verbose_name='Vị trí')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('fault', 'Hỏng'), ('maintenance', 'Đang bảo trì'), ('off', 'Tắt')], default='active', max_length=15, verbose_name='Trạng thái')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Ngày lắp đặt')),
                ('managing_unit', models.CharField(blank=True, max_length=200, verbose_name='Đơn vị quản lý')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('last_bulb_change', models.DateField(blank=True, null=True, verbose_name='Thay bóng lần cuối')),
                ('operating_hours', models.CharField(default='24/7', max_length=50, verbose_name='Giờ hoạt động')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_lights', to='infrastructure.road', verbose_name='Tuyến đường')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.managementzone')),
            ],
            options={
                'verbose_name': 'Đèn giao thông',
                'verbose_name_plural': 'Đèn giao thông',
            },
        ),
    ]
