# Generated by Django 6.0.3 on 2026-03-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('length_m', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('width_m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(default='GOOD', max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potholes', to='infrastructure.road')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
