# Generated by Django 6.0.3 on 2026-03-09 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='surface_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='infrastructure.area'),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Khẩn cấp')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Mới phát hiện'), ('IN_PROGRESS', 'Đang xử lý'), ('FIXED', 'Đã sửa')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='road',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roads', to='infrastructure.area'),
        ),
        migrations.AlterField(
            model_name='road',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Tốt'), ('FAIR', 'Trung bình'), ('POOR', 'Kém'), ('DAMAGED', 'Hư hỏng')], default='GOOD', max_length=20),
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('FAULT', 'Lỗi'), ('OFFLINE', 'Mất kết nối'), ('MAINTENANCE', 'Bảo trì')], default='ACTIVE', max_length=20)),
                ('installed_year', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_lights', to='infrastructure.area')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
