# Generated by Django 6.0.3 on 2026-03-09 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0002_road_surface_type_alter_area_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_name', models.CharField(blank=True, max_length=100)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weather_main', models.CharField(blank=True, max_length=100)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.area')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
