# Generated by Django 6.0.3 on 2026-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Vị trí')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(verbose_name='Nhiệt độ (°C)')),
                ('humidity', models.IntegerField(verbose_name='Độ ẩm (%)')),
                ('wind_speed', models.FloatField(default=0, verbose_name='Tốc độ gió (km/h)')),
                ('wind_direction', models.CharField(blank=True, max_length=10, verbose_name='Hướng gió')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('rain_mm', models.FloatField(default=0, verbose_name='Lượng mưa (mm)')),
                ('pressure_hpa', models.FloatField(blank=True, null=True, verbose_name='Áp suất (hPa)')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Nguy hiểm')),
                ('source', models.CharField(default='manual', max_length=50, verbose_name='Nguồn dữ liệu')),
                ('recorded_at', models.DateTimeField(verbose_name='Thời gian đo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dữ liệu thời tiết',
                'verbose_name_plural': 'Dữ liệu thời tiết',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Vị trí')),
                ('forecast_date', models.DateField(verbose_name='Ngày dự báo')),
                ('temp_min', models.FloatField(verbose_name='Nhiệt độ thấp nhất')),
                ('temp_max', models.FloatField(verbose_name='Nhiệt độ cao nhất')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('rain_probability', models.IntegerField(default=0, verbose_name='Xác suất mưa (%)')),
                ('is_warning', models.BooleanField(default=False, verbose_name='Cảnh báo')),
                ('warning_message', models.TextField(blank=True, verbose_name='Thông điệp cảnh báo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dự báo thời tiết',
                'verbose_name_plural': 'Dự báo thời tiết',
                'ordering': ['forecast_date'],
            },
        ),
    ]
