# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả sự cố')),
                ('incident_type', models.CharField(choices=[('road_damage', 'Hư hỏng đường'), ('pothole', 'Ổ gà'), ('traffic_light', 'Đèn giao thông'), ('drainage', 'Thoát nước'), ('bridge', 'Cầu cống'), ('sign', 'Biển báo'), ('lighting', 'Chiếu sáng'), ('other', 'Khác')], max_length=20, verbose_name='Loại sự cố')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=10, verbose_name='Mức độ ưu tiên')),
                ('status', models.CharField(choices=[('pending', 'Chờ tiếp nhận'), ('received', 'Đã tiếp nhận'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=15, verbose_name='Trạng thái')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Phản ánh ẩn danh')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phân công')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('estimated_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Chi phí dự kiến (VNĐ)')),
                ('actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Chi phí thực tế (VNĐ)')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('processing_note', models.TextField(blank=True, verbose_name='Ghi chú xử lý')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Phản ánh trùng')),
                ('citizen_rating', models.IntegerField(blank=True, null=True, verbose_name='Đánh giá của người dân (1-5)')),
                ('citizen_feedback', models.TextField(blank=True, verbose_name='Phản hồi người dân')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='maintenance.maintenancerequest', verbose_name='Trùng với')),
                ('infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='infrastructure.infrastructure', verbose_name='Hạ tầng liên quan')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='infrastructure.road', verbose_name='Tuyến đường')),
            ],
            options={
                'verbose_name': 'Yêu cầu bảo trì',
                'verbose_name_plural': 'Yêu cầu bảo trì',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance/photos/', verbose_name='Ảnh')),
                ('phase', models.CharField(choices=[('before', 'Trước'), ('after', 'Sau'), ('during', 'Trong quá trình')], max_length=10, verbose_name='Giai đoạn')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Ảnh bảo trì',
                'verbose_name_plural': 'Ảnh bảo trì',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('scheduled_date', models.DateField(verbose_name='Ngày lên kế hoạch')),
                ('status', models.CharField(choices=[('planned', 'Kế hoạch'), ('confirmed', 'Đã xác nhận'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('postponed', 'Hoãn')], default='planned', max_length=15, verbose_name='Trạng thái')),
                ('estimated_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Chi phí dự kiến')),
                ('is_periodic', models.BooleanField(default=False, verbose_name='Định kỳ')),
                ('period_days', models.IntegerField(blank=True, null=True, verbose_name='Chu kỳ (ngày)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='maintenance_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='infrastructure.infrastructure')),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='infrastructure.road')),
            ],
            options={
                'verbose_name': 'Lịch bảo trì',
                'verbose_name_plural': 'Lịch bảo trì',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='maintenance/videos/', verbose_name='Video')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='maintenance.maintenancerequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video bảo trì',
            },
        ),
    ]
