# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên trung tâm')),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trung tâm đăng kiểm',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Biển số xe')),
                ('vehicle_type', models.CharField(choices=[('car', 'Ô tô'), ('motorcycle', 'Xe máy'), ('truck', 'Xe tải'), ('bus', 'Xe buýt'), ('other', 'Khác')], max_length=15, verbose_name='Loại xe')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Hãng xe')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Màu sắc')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Năm sản xuất')),
                ('chassis_number', models.CharField(blank=True, max_length=50, verbose_name='Số khung')),
                ('engine_number', models.CharField(blank=True, max_length=50, verbose_name='Số máy')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phương tiện',
                'verbose_name_plural': 'Phương tiện',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Lịch hẹn')),
                ('status', models.CharField(choices=[('pending', 'Chờ kiểm tra'), ('in_progress', 'Đang kiểm tra'), ('passed', 'Đạt'), ('failed', 'Không đạt'), ('needs_repair', 'Cần sửa chữa'), ('cancelled', 'Đã hủy')], default='pending', max_length=15, verbose_name='Trạng thái')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Ghi chú kỹ thuật')),
                ('defects', models.TextField(blank=True, verbose_name='Lỗi phát hiện')),
                ('repair_required', models.TextField(blank=True, verbose_name='Yêu cầu sửa chữa')),
                ('repair_result', models.TextField(blank=True, verbose_name='Kết quả sửa chữa')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí đăng kiểm (VNĐ)')),
                ('is_fee_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Số giấy chứng nhận')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_done', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_inspection.inspectioncenter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicle_inspection.vehicle')),
            ],
            options={
                'verbose_name': 'Lịch đăng kiểm',
                'verbose_name_plural': 'Lịch đăng kiểm',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
