# Generated by Django 6.0.3 on 2026-05-13 05:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectioncenter',
            options={'ordering': ['name'], 'verbose_name': 'Trung tâm đăng kiểm', 'verbose_name_plural': 'Trung tâm đăng kiểm'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phương tiện', 'verbose_name_plural': 'Phương tiện'},
        ),
        migrations.AddField(
            model_name='inspectioncenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectioncenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_inspection.inspectioncenter', verbose_name='Trung tâm'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Số giấy chứng nhận'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Phí đăng kiểm (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Cán bộ kiểm tra'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='is_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Đã thanh toán phí'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='Ngày hẹn'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ kiểm tra'), ('in_progress', 'Đang kiểm tra'), ('passed', 'Đạt'), ('failed', 'Không đạt'), ('needs_repair', 'Cần sửa chữa'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=15, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicle_inspection.vehicle', verbose_name='Phương tiện'),
        ),
        migrations.AlterField(
            model_name='inspectioncenter',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='inspectioncenter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hoạt động'),
        ),
        migrations.AlterField(
            model_name='inspectioncenter',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên trung tâm'),
        ),
        migrations.AlterField(
            model_name='inspectioncenter',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hoạt động'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, help_text='Ví dụ: 43A-12345', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_license_plate', message='Biển số không hợp lệ. Vui lòng nhập biển số Đà Nẵng, ví dụ: 43A-12345 hoặc 43A-123.45', regex='^43[A-Z0-9]{1,2}-?\\d{3}\\.?\\d{2}$|^43[A-Z0-9]{1,2}-?\\d{4}$')], verbose_name='Biển số xe'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Chủ xe'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['vehicle', 'status'], name='vehicle_ins_vehicle_8b1604_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['scheduled_date'], name='vehicle_ins_schedul_28e846_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='vehicle_ins_status_19a642_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner', 'is_active'], name='vehicle_ins_owner_i_f56d27_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicle_ins_license_852598_idx'),
        ),
    ]
