# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Tự động')),
                ('frequency', models.CharField(choices=[('manual', 'Thủ công'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], default='manual', max_length=10, verbose_name='Tần suất')),
                ('time_of_day', models.TimeField(blank=True, null=True, verbose_name='Giờ backup')),
                ('max_backups', models.IntegerField(default=10, verbose_name='Số lượng backup tối đa')),
                ('include_media', models.BooleanField(default=True, verbose_name='Bao gồm media')),
                ('compress', models.BooleanField(default=True, verbose_name='Nén file')),
                ('encrypt', models.BooleanField(default=False, verbose_name='Mã hóa')),
                ('upload_to_cloud', models.BooleanField(default=False, verbose_name='Upload lên cloud')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình backup',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(default='full', max_length=20, verbose_name='Loại')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn')),
                ('file_size_mb', models.FloatField(default=0, verbose_name='Kích thước (MB)')),
                ('status', models.CharField(choices=[('running', 'Đang chạy'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('paused', 'Tạm dừng')], default='running', max_length=10, verbose_name='Trạng thái')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Đã mã hóa')),
                ('is_compressed', models.BooleanField(default=False, verbose_name='Đã nén')),
                ('error_message', models.TextField(blank=True, verbose_name='Lỗi')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bản backup',
                'verbose_name_plural': 'Bản backup',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='success', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('restored_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restores', to='backup.backuprecord')),
                ('restored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử restore',
                'ordering': ['-restored_at'],
            },
        ),
    ]
