# Generated by Django 6.0.3 on 2026-03-09 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('infrastructure', '0002_road_surface_type_alter_area_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='infrastructure.area'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='incidents.incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('ROAD_DAMAGE', 'Đường hư hỏng'), ('FLOOD', 'Ngập lụt'), ('TRAFFIC_LIGHT', 'Đèn giao thông lỗi'), ('BRIDGE_DAMAGE', 'Cầu hư hỏng'), ('OTHER', 'Khác')], max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Khẩn cấp')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('NEW', 'Mới'), ('VERIFIED', 'Đã xác minh'), ('ASSIGNED', 'Đã phân công'), ('RESOLVED', 'Đã xử lý'), ('REJECTED', 'Từ chối')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentattachment',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10),
        ),
    ]
