# Generated by Django 6.0.3 on 2026-04-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('notification_type', models.CharField(choices=[('maintenance', 'Bảo trì'), ('flood', 'Ngập lụt'), ('system', 'Hệ thống'), ('emergency', 'Khẩn cấp'), ('general', 'Thông thường'), ('reminder', 'Nhắc nhở')], default='general', max_length=15, verbose_name='Loại')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID đối tượng liên quan')),
                ('action_url', models.CharField(blank=True, max_length=200, verbose_name='URL hành động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Đọc lúc')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('system', 'Hệ thống')], max_length=10, verbose_name='Kênh')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='Số người nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
